version: "3.8"

services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=*
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000

  express-app:
    build:
      context: ./express-server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./express-server:/app
      - /app/node_modules
    depends_on:
      - chromadb
    env_file:
      - ./express-server/.env

volumes:
  chroma-data:
